# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fin < Formula
  desc "Agent-native CLI for Plaid / personal banking data"
  homepage "https://github.com/kdubb1337/fin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.1.0/fin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5dfe1088fceb722754dc707049b8061c92e4f5b791c0f82aa6d60f8e1e2d1023"

      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.1.0/fin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "b0b7fc5fabd6927b0fb1bb60bd33e5b9343c4548fddfdec44b50ffa180e1fa74"

      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.1.0/fin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "cc21fa2978d24aedb28633208972bbfd4fecd0bdc1705f0cfebb6476e452f534"
      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.1.0/fin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "e440ad0c36fb8a39f0c1c092e94ba8f4613a9dee80648e17a1e7dfb0994d58bd"
      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/fin", "--version"
  end
end
