# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fin < Formula
  desc "Agent-native CLI for Plaid / personal banking data"
  homepage "https://github.com/kdubb1337/fin-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.3.1/fin-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "aba1ce3b4bbdba174b84158523701606afd8374acba906c9be2ae808702e96f9"

      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.3.1/fin-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "fee8b32ff9c7332e1780d6b89310b76733eb18a4a8d72c025b8fcc525c77273d"

      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.3.1/fin-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "7f41c0bbc62445bfabcb23f4045d3b5644e34e0807f5322a22be26f491dba5e2"
      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/fin-cli/releases/download/v0.3.1/fin-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "492f943601f640954a4c21acc5b356c8180f481bf14abc016a085a4dd7fedf7b"
      define_method(:install) do
        bin.install "fin"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/fin", "--version"
  end
end
