# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghub < Formula
  desc "Agent-native CLI for GitHub"
  homepage "https://github.com/kdubb1337/ghub"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.1/ghub_0.1.1_darwin_amd64.tar.gz"
      sha256 "254bbb17eac1c252f6bfa583c73f505aad87310002549f7f1104397c6ffaa243"

      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.1/ghub_0.1.1_darwin_arm64.tar.gz"
      sha256 "8964cc47510772ce2ec922ba6da7f3046af30c8faaa0ab2588af6679de1fb19a"

      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.1/ghub_0.1.1_linux_amd64.tar.gz"
      sha256 "fc75e067187e28a116479d241db2c2e65308f0543833e6ea415918ad92cc55a7"
      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.1/ghub_0.1.1_linux_arm64.tar.gz"
      sha256 "4cee3eeea683cbce9257bf4dbea9950be2cfd6dd5533001208f87fc343ee5095"
      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/ghub", "--version"
  end
end
