# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghub < Formula
  desc "Agent-native CLI for GitHub"
  homepage "https://github.com/kdubb1337/ghub"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.0/ghub_0.1.0_darwin_amd64.tar.gz"
      sha256 "a43a7cf89a6d5fa40d6d797e11837b00b9b8098756c253b976ec9fdccb176061"

      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.0/ghub_0.1.0_darwin_arm64.tar.gz"
      sha256 "2e26151d858130efb43a8837381670f39112bb5df4f16483f5d5b7c1b4c9dcc5"

      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.0/ghub_0.1.0_linux_amd64.tar.gz"
      sha256 "7942bace1a3ccdc4236367a635db036c156269d54b883d372ddb64698a091045"
      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/ghub/releases/download/v0.1.0/ghub_0.1.0_linux_arm64.tar.gz"
      sha256 "387341e2339c0dfd9073fd631119c71522145b15a59ccceab49483a076f4cb71"
      define_method(:install) do
        bin.install "ghub"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/ghub", "--version"
  end
end
