# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phog < Formula
  desc "Agent-native CLI for PostHog — query events, web activity, insights, and persons via the PostHog API"
  homepage "https://github.com/kdubb1337/phog-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.3.1/phog-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "09631888a28ab6202f2b4a253453498a82e509159166ae1ae2e5f8e4e51242fe"

      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.3.1/phog-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "2533b4ef9563d3c08340d47b5f07d3e5c66d8a95ded7ca5a49609288eb27fc2d"

      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.3.1/phog-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "5da9dca1941a1f1fd7ca848590b87e401061b18437a961ad0f986150e7e97c18"
      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.3.1/phog-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "3ae1678df1cf0dc636d7ddc2e44dfacf36b657cf1b112dd13bca909fc07e6e9c"
      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/phog", "--version"
  end
end
