# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phog < Formula
  desc "Agent-native CLI for PostHog — query events, web activity, insights, and persons via the PostHog API"
  homepage "https://github.com/kdubb1337/phog-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.1.0/phog-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "2f84588a11dac2d4c69c50cdeb77e50607f031b9c5f6fa1b0b77b09b1882a865"

      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.1.0/phog-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "3079a86788c7941f88a129c536618f0b7ea6268b83142895ebb6ffde9c1b01fc"

      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.1.0/phog-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "cac6a24e4808cbeba07ab35f628f623223d323ee6f1196dae45a0381549f1fc9"
      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/phog-cli/releases/download/v0.1.0/phog-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ca97610949c0c5b37f55a3f6f15ce9c0145ec4e79a7f71769741c9e0a823aeda"
      define_method(:install) do
        bin.install "phog"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/phog", "--version"
  end
end
