# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpod < Formula
  desc "Agent-native CLI for RunPod (GPU pods, network volumes, GPU type discovery)"
  homepage "https://github.com/kdubb1337/rpod-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.6.0/rpod-cli_0.6.0_darwin_amd64.tar.gz"
      sha256 "36fb9cefe5b22285020d606d1404ea41e6535c01b26c340da188d17fd4b9f770"

      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.6.0/rpod-cli_0.6.0_darwin_arm64.tar.gz"
      sha256 "d8308f9c2951c428712dc13ed81c9cc4c43ef7438ab04f246b0b1ad9541749e8"

      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.6.0/rpod-cli_0.6.0_linux_amd64.tar.gz"
      sha256 "80e07576e4955b04d8a92951c4217cc2748a012984402b2e6f6131b3734a6a25"
      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.6.0/rpod-cli_0.6.0_linux_arm64.tar.gz"
      sha256 "23ffb1aa58a7475c5c01ffabbc7f2af72e260ae854db71758c760943ee9bfe9a"
      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/rpod", "--version"
  end
end
