# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpod < Formula
  desc "Agent-native CLI for RunPod (GPU pods, network volumes, GPU type discovery)"
  homepage "https://github.com/kdubb1337/rpod-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.3.0/rpod-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "921ebfde8121b65a1e284665ca74090da0d499af71125f4ae957dfe231bb462f"

      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.3.0/rpod-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "aa03f4153a79ffcfc173c16a7b408da09a139ebc4eaa5b719dae8176f9b3aa20"

      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.3.0/rpod-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "b94b62115ba563df365e3d704283f00caa04f12d4c5203da8f53d7844e72fd4a"
      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/rpod-cli/releases/download/v0.3.0/rpod-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "1a97eab94de26c0a8a68d9d99e5329c8c6c184c0f78162fa0fcdf3151453a3bd"
      define_method(:install) do
        bin.install "rpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/rpod", "--version"
  end
end
