# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpod < Formula
  desc "Agent-native CLI for RunPod (GPU pods, network volumes, GPU type discovery)"
  homepage "https://github.com/kdubb1337/runpod-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdubb1337/runpod-cli/releases/download/v0.1.0/runpod-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "8ad88bfc7a426bf84a8d88f12f66f555e3ecb9fb36d6a00e4a21408c4ac4a648"

      define_method(:install) do
        bin.install "runpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdubb1337/runpod-cli/releases/download/v0.1.0/runpod-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "957c8a0f6a0fe132f9e6eb83d6387ea7b305f881449c8152f594eec11b3aac98"

      define_method(:install) do
        bin.install "runpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/runpod-cli/releases/download/v0.1.0/runpod-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "2271801874903565b7ee0ade05e0d9b4314f0be1851fa92138a50555891d8469"
      define_method(:install) do
        bin.install "runpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdubb1337/runpod-cli/releases/download/v0.1.0/runpod-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "a16ed5d815202c998b4391d97e9de9ec045e9d7be331ebb4e4c4cebc9d20de61"
      define_method(:install) do
        bin.install "runpod"
        pkgshare.install "skills" if File.directory?("skills")
      end
    end
  end

  test do
    system "#{bin}/runpod", "--version"
  end
end
